-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Bancos"
(
    id serial,
    nombre text,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Clientes"
(
    id serial,
    rut integer,
    dv text,
    nombre text,
    "apellidoP" text,
    "apellidoM" text,
    email text,
    telefono text,
    direccion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Cuentas"
(
    id serial,
    "nroCuenta" integer,
    saldo integer,
    "lineaCredito" integer,
    "fechaApertura" date,
    "montoGiroDiario" integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Transacciones"
(
    id serial,
    "fechaTransaccion" date,
    "fechaFinalizacion" date,
    monto integer,
    "idCuentaOrigen" serial,
    "idCuentaDestino" serial,
    "idTipoTransaccion" serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."tipoTrasaccion"
(
    id serial,
    nombre text,
    descripcion text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EstadoCuentas"
(
    id serial,
    "balanceInicial" integer,
    "balanceFinal" integer,
    "nroTransaccionesRealizadas" integer,
    "fechaFacturacion" date,
    "mesEstadoCuenta" integer,
    "idCliente" serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Bancos_Clientes"
(
    id serial,
    "idCliente" serial,
    "idBanco" serial,
    "idCuenta" serial,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Transacciones"
    ADD FOREIGN KEY ("idTipoTransaccion")
    REFERENCES public."tipoTrasaccion" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transacciones"
    ADD FOREIGN KEY ("idCuentaOrigen")
    REFERENCES public."Cuentas" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Transacciones"
    ADD FOREIGN KEY ("idCuentaDestino")
    REFERENCES public."Cuentas" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EstadoCuentas"
    ADD FOREIGN KEY ("idCliente")
    REFERENCES public."Clientes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bancos_Clientes"
    ADD FOREIGN KEY ("idBanco")
    REFERENCES public."Bancos" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bancos_Clientes"
    ADD FOREIGN KEY ("idCliente")
    REFERENCES public."Clientes" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bancos_Clientes"
    ADD FOREIGN KEY ("idCuenta")
    REFERENCES public."Cuentas" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;